import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import type * as vscode from 'vscode'
import type { RuntimeConfig } from './config'

export const GENERATED_FILE_NAME = 'composer-zoom.js'

const RUNTIME_SOURCE_PATH = path.join('runtime', 'composerZoom.js')

export interface RuntimeWriteResult {
  filePath: string
  didChange: boolean
}

// Assigns onto `window` rather than declaring a variable: Custom UI Style
// concatenates every injected `.js` import into one module scope, where a
// top-level name could collide with another extension's script.
export const buildConfigPrelude = (config: RuntimeConfig): string =>
  [
    '// Generated by the Composer Zoom extension from your settings.',
    '// Edits here are overwritten; change the composerZoom.* settings instead.',
    // Terminated explicitly. The runtime appended below opens with `(`, which
    // without this semicolon continues the expression and calls the config
    // object literal, throwing before anything installs.
    `window.__composerZoomConfig = ${JSON.stringify(config, null, 2)};`,
    '',
    '',
  ].join('\n')

const readExisting = async (filePath: string): Promise<string | null> => {
  try {
    return await fs.readFile(filePath, 'utf-8')
  } catch {
    return null
  }
}

// Generated into global storage rather than the extension folder, whose path
// carries the version number and therefore moves on every update.
export const writeRuntimeFile = async (
  context: vscode.ExtensionContext,
  config: RuntimeConfig,
): Promise<RuntimeWriteResult> => {
  const source = await fs.readFile(path.join(context.extensionPath, RUNTIME_SOURCE_PATH), 'utf-8')
  const contents = `${buildConfigPrelude(config)}${source}`

  const directory = context.globalStorageUri.fsPath
  const filePath = path.join(directory, GENERATED_FILE_NAME)

  if ((await readExisting(filePath)) === contents) return { filePath, didChange: false }

  await fs.mkdir(directory, { recursive: true })
  await fs.writeFile(filePath, contents, 'utf-8')
  return { filePath, didChange: true }
}
